name: Node.js CI/CD Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'
        registry-url: "https://registry.npmjs.org"
    - name: Get next version
      uses: reecetech/version-increment@2023.9.3
      id: version
      with:
        scheme: semver
        increment: patch
    - name: Update package.json
      run: npm version ${{ steps.version.outputs.version }} --no-git-tag-version --allow-same-version
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        title: Release v${{ steps.version.outputs.version }}
        tag_name: v${{ steps.version.outputs.version }}
        files: |
          dist/*
          src/*
          package.json
          README.md
          tsconfig.json
          tsconfig-cjs.json
          .eslintrc.js
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}